FROM python:3.9-slim

WORKDIR /app

# Copy application and test code
COPY ./app /app/dags
COPY ./tests /app/tests

# Run tests
CMD ["python", "-m", "unittest", "discover", "-s", "/app/tests", "-p", "test_*.py"]
